services:
  OIDCWardenPrebuild:
    profiles: ["playwright", "oidcwarden"]
    container_name: playwright_oidc_warden_prebuilt
    image: playwright_oidc_warden_prebuilt
    build:
      context: ..
      dockerfile: Dockerfile
    entrypoint: /bin/bash
    restart: "no"

  OIDCWarden:
    profiles: ["playwright", "oidcwarden"]
    container_name: playwright_oidc_warden_main-${ENV:-dev}
    image: playwright_oidc_warden_main-${ENV:-dev}
    network_mode: "host"
    build:
      context: compose/warden
      dockerfile: Dockerfile
      args:
        REPO_URL: ${PW_WV_REPO_URL:-}
        COMMIT_HASH: ${PW_WV_COMMIT_HASH:-}
    env_file: ${DC_ENV_FILE:-.env}
    environment:
      - DATABASE_URL
      - I_REALLY_WANT_VOLATILE_STORAGE
      - LOG_LEVEL
      - LOGIN_RATELIMIT_MAX_BURST
      - ORGANIZATION_INVITE_AUTO_ACCEPT
      - ORG_GROUPS_ENABLED
      - SMTP_HOST
      - SMTP_FROM
      - SMTP_DEBUG
      - SSO_DEBUG_TOKENS
      - SSO_ENABLED
      - SSO_FRONTEND
      - SSO_ONLY
      - SSO_ORGANIZATIONS_ENABLED
      - SSO_ORGANIZATIONS_REVOCATION
      - SSO_ROLES_DEFAULT_TO_USER
      - SSO_ROLES_ENABLED
      - SSO_SCOPES
    restart: "no"
    depends_on:
      - OIDCWardenPrebuild

  Playwright:
    profiles: ["playwright"]
    container_name: playwright_oidc_playwright_main
    image: playwright_oidc_playwright_main
    network_mode: "host"
    build:
      context: .
      dockerfile: compose/playwright/Dockerfile
    environment:
      - PW_WV_REPO_URL
      - PW_WV_COMMIT_HASH
    restart: "no"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/project

  Mariadb:
    profiles: ["playwright"]
    container_name: playwright_mariadb
    image: mariadb:11.2.4
    env_file: test.env
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
    ports:
      - ${MARIADB_PORT}:3306

  Mysql:
    profiles: ["playwright"]
    container_name: playwright_mysql
    image: mysql:8.4.1
    env_file: test.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 10s
      interval: 10s
    ports:
      - ${MYSQL_PORT}:3306

  Postgres:
    profiles: ["playwright"]
    container_name: playwright_postgres
    image: postgres:16.3
    env_file: test.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
    ports:
      - ${POSTGRES_PORT}:5432

  Maildev:
    profiles: ["oidcwarden", "maildev"]
    container_name: maildev
    image: timshel/maildev:3.0.4
    ports:
      - ${SMTP_PORT}:1025
      - 1080:1080

  Keycloak:
    profiles: ["keycloak", "oidcwarden"]
    container_name: keycloak-main-${ENV:-dev}
    image: quay.io/keycloak/keycloak:25.0.4
    network_mode: "host"
    command:
      - start-dev
    env_file: ${DC_ENV_FILE:-.env}

  KeycloakSetup:
    profiles: ["keycloak", "oidcwarden"]
    container_name: keycloakSetup-main-${ENV:-dev}
    image: keycloak_setup-main-${ENV:-dev}
    build:
      context: compose/keycloak
      dockerfile: Dockerfile
      args:
        KEYCLOAK_VERSION: 26.3.0
    network_mode: "host"
    depends_on:
      - Keycloak
    restart: "no"
    env_file: ${DC_ENV_FILE:-.env}
